### ISSUE TITLE
权重文件

### ISSUE THREAD

**Issue by PZ04111618** [ssocean/UNet-Binarization#1]
老师您好，请问可以用一下你的训练好的权重文件吗？我想学习一下，谢谢

**Comment by ssocean** [comment]
感谢关注~ 权重文件：链接：https://pan.baidu.com/s/1iX8CqnpqkQyasIRwa78l3Q?pwd=ig3c 
提取码：ig3c  这个是用于顺序预测的哈

**Comment by PZ04111618** [comment]
> 感谢关注~ 权重文件：链接：https://pan.baidu.com/s/1iX8CqnpqkQyasIRwa78l3Q?pwd=ig3c 提取码：ig3c 这个是用于顺序预测的哈
谢谢您的回答，祝您生活愉快，科研顺利！
